Repository milvus-io/milvus-sdk-node, pull requests merged in 2021-08, with the labels that each got.

#23 Refactor code structure
  example/BinarySearch.ts
  example/Collection.ts
  example/Insert.ts
  example/Search.ts
  milvus/Client.ts
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/index.ts
  milvus/types.ts
  milvus/types/Collection.ts
  milvus/types/Index.ts
  milvus/types/Response.ts
  milvus/types/Search.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/Partition.spec.ts
  test/Search.spec.ts
Labels: size/XXL

#29 add version api
  example/Collection.ts
  milvus/index.ts
  package.json
  tsconfig.json
Labels: size/S

#30 fix build
  helper.js
  package.json
Labels: size/S

#31 fix protobuf
  milvus/Collection.ts
  milvus/Data.ts
Labels: size/XS

#32 update version
  package.json
Labels: size/XS

#33 fix get version in sdk
  example/BinarySearch.ts
  helper.js
  milvus/index.ts
  sdk.json
Labels: size/M

#34 update version
  package.json
Labels: size/XS

#36 Run ut in github action when open pull request
  .github/workflows/check.yml
  .github/workflows/ci.yml
  .gitignore
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/const/index.html
  coverage/lcov-report/const/index.ts.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/milvus/Client.ts.html
  coverage/lcov-report/milvus/Collection.ts.html
  coverage/lcov-report/milvus/Data.ts.html
  coverage/lcov-report/milvus/MilvusIndex.ts.html
  coverage/lcov-report/milvus/Partition.ts.html
  coverage/lcov-report/milvus/const/ErrorCode.ts.html
  coverage/lcov-report/milvus/const/ErrorReason.ts.html
  coverage/lcov-report/milvus/const/index.html
  coverage/lcov-report/milvus/index.html
  coverage/lcov-report/milvus/index.ts.html
  coverage/lcov-report/milvus/response-types.ts.html
  coverage/lcov-report/milvus/types.ts.html
  coverage/lcov-report/milvus/types/Collection.ts.html
  coverage/lcov-report/milvus/types/Common.ts.html
  coverage/lcov-report/milvus/types/Response.ts.html
  coverage/lcov-report/milvus/types/index.html
  coverage/lcov-report/milvus/utils/Blob.ts.html
  coverage/lcov-report/milvus/utils/Format.ts.html
  coverage/lcov-report/milvus/utils/Validate.ts.html
  coverage/lcov-report/milvus/utils/index.html
  coverage/lcov-report/milvus/utils/index.ts.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/utils/index.html
  coverage/lcov-report/utils/index.ts.html
  coverage/lcov.info
  example/Collection.ts
  milvus/index.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Partition.spec.ts
Labels: size/XXL

#38 Add doc comments
  .DS_Store
  README.md
  build.js
  doc.js
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/index.ts
  milvus/types.ts
  milvus/types/Collection.ts
  milvus/types/Index.ts
  milvus/types/Response.ts
  package.json
  test/Index.spec.ts
  test/Insert.spec.ts
  typedoc.json
  yarn-error.log
  yarn.lock
Labels: size/XXL

#39 update test and add close connection api;
  build.js
  grpc-proto/milvus.proto
  milvus/Collection.ts
  milvus/index.ts
  package.json
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/MilvusClient.spec.ts
  test/Partition.spec.ts
  test/Search.spec.ts
Labels: size/M

#41 Update version
  package.json
Labels: size/XS

#42 Update updateDoc.yml
  .github/workflows/updateDoc.yml
Labels: size/XS

#43 fix doc.js
  doc.js
  package.json
Labels: size/XS

#44 fix doc
  doc.js
  package.json
  test/Insert.spec.ts
Labels: size/S

#47 Refactor show collections response
  example/LoadCollectionStatus.ts
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/types.ts
  milvus/types/Collection.ts
  milvus/types/Response.ts
  test/Collection.spec.ts
Labels: size/L

#49 [skip ci] Update API Reference
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
Labels: size/L

#48 Refactor key value pairs and improve query response
  example/BinarySearch.ts
  example/Collection.ts
  example/Insert.ts
  example/LoadCollectionStatus.ts
  example/Search.ts
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/index.ts
  milvus/types.ts
  milvus/types/Collection.ts
  milvus/types/Index.ts
  milvus/types/Response.ts
  milvus/types/Search.ts
  milvus/utils/Format.ts
  milvus/utils/Validate.ts
  package.json
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/Partition.spec.ts
  test/Search.spec.ts
  utils/test.ts
Labels: size/XXL

#50 Update ci and export more types
  .github/workflows/check.yml
  .github/workflows/ci.yml
  .github/workflows/merge.yml
  example/Collection.ts
  milvus/types.ts
  milvus/types/Index.ts
  milvus/types/Search.ts
Labels: size/M
