Repository milvus-io/milvus-sdk-node, pull requests merged in 2022-09, with the labels that each got.

#105 support timeout for other apis
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/User.ts
  milvus/types/Data.ts
  milvus/types/Index.ts
  milvus/types/Partition.ts
  milvus/types/Search.ts
  milvus/types/User.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Index.spec.ts
  test/Partition.spec.ts
  test/User.spec.ts
Labels: size/L

#106 fix consistency_level bug
  example/Collection.ts
  milvus/Collection.ts
Labels: size/S

#107 Fix getIndexBuildProgress param
  milvus/MilvusIndex.ts
  package.json
Labels: size/XS

#108 Update create collection with invalid consistency level param and its default value
  milvus/Collection.ts
  test/Collection.spec.ts
Labels: size/S
