Repository milvus-io/milvus-sdk-node, pull requests merged in 2022-12, with the labels that each got.

#121 Add more index testing
  milvus/types/Index.ts
  test/Index.spec.ts
Labels: size/L

#120 sync up proto types
  milvus/types/Common.ts
Labels: size/L

#122 add alias test
  test/Collection.spec.ts
Labels: size/M

#123 fix binary search case
  test/BinarySearch.spec.ts
Labels: size/S

#125 fix failed test on milvus 2.2.1
  test/Data.spec.ts
Labels: size/XS

#124 fix: perf issue, do not load proto on each search() call
  milvus/Data.ts
Labels: size/XS, lgtm
