Repository milvus-io/milvus-sdk-node, pull requests merged in 2023-08, with the labels that each got.

#214 fix: delete entities when the primary key is string
  milvus/grpc/Data.ts
Labels: size/XS

#215 fix issue 26036
  milvus/grpc/Data.ts
Labels: size/XS

#216 Adjust insert default timeout
  milvus/grpc/Data.ts
  milvus/utils/Function.ts
  package.json
Labels: size/S

#219 Node example improvments
  examples/milvus/DataQuery.ts
  examples/milvus/Database.ts
Labels: size/XS

#223 fix: issue-222
  milvus/grpc/Data.ts
Labels: size/XS

#224 support consine for milvus2.3
  milvus/const/Milvus.ts
  test/Index.spec.ts
Labels: size/M

#227 Default value
  milvus/grpc/Collection.ts
  milvus/grpc/Data.ts
  milvus/types/Collection.ts
  milvus/utils/Format.ts
  milvus/utils/Function.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Orm.spec.ts
  test/build/Collection.spec.ts
  test/tools/index.ts
Labels: size/L

#228 Upsert
  milvus/grpc/Data.ts
  milvus/types/Response.ts
  test/Upsert.spec.ts
Labels: size/L

#230 Range search
  milvus/grpc/Data.ts
  test/Data.spec.ts
Labels: size/S

#229 add new gpu index
  milvus/const/Milvus.ts
Labels: size/XS

#233 update langchain example
  examples/LangChain/LangChain.js
  examples/LangChain/package.json
  examples/LangChain/yarn.lock
Labels: size/XL

#236 Add Scann index
  milvus/const/Milvus.ts
  test/Index.spec.ts
Labels: size/S

#237 make proto file path configurable
  milvus/grpc/BaseClient.ts
  milvus/grpc/GrpcClient.ts
  milvus/types/Client.ts
Labels: size/M

#238 support count('*')
  milvus/grpc/Data.ts
  package.json
  test/Data.spec.ts
Labels: size/S
