Repository milvus-io/milvus-sdk-node, pull requests merged in 2023-07, with the labels that each got.

#201 upgrade grpc version
  package.json
  yarn.lock
Labels: size/S

#205 add ingore growing, fix #204
  milvus/grpc/Data.ts
  milvus/types/Data.ts
Labels: size/XS

#203 add getPersistentSegmentInfo
  milvus/grpc/Data.ts
  milvus/types/Data.ts
  test/Data.spec.ts
Labels: size/M

#206 support partition_key_field for createCollection
  milvus/types/Collection.ts
  milvus/utils/Format.ts
  test/PartitionKey.spec.ts
Labels: size/M

#210 fix grpc node version
  package.json
  test/BinarySearch.spec.ts
  yarn.lock
Labels: size/L

#211 docs: fix langchain example link
  README.md
Labels: size/XS

#212 by default, it should list username for listRoles
  milvus/grpc/User.ts
  milvus/types/User.ts
Labels: size/S
