Repository milvus-io/milvus-sdk-node, pull requests merged in 2023-12, with the labels that each got.

#261 Support connection pool
  jest.config.js
  milvus/MilvusClient.ts
  milvus/const/client.ts
  milvus/const/defaults.ts
  milvus/grpc/BaseClient.ts
  milvus/grpc/Collection.ts
  milvus/grpc/Data.ts
  milvus/grpc/Database.ts
  milvus/grpc/GrpcClient.ts
  milvus/grpc/MilvusIndex.ts
  milvus/grpc/Partition.ts
  milvus/grpc/Resource.ts
  milvus/grpc/User.ts
  milvus/types/Client.ts
  milvus/utils/Function.ts
  package.json
  test/grpc/Collection.spec.ts
  test/grpc/MilvusClient.spec.ts
  test/utils/Function.spec.ts
  yarn.lock
Labels: size/XL

#262 update delete api, comment, types, test
  milvus/grpc/Data.ts
  milvus/orm/Collection.ts
  milvus/types/Data.ts
  test/grpc/Data.spec.ts
  test/grpc/Orm.spec.ts
Labels: size/M

#263 update query/get api/query comments and test
  milvus/grpc/Data.ts
  milvus/types/Data.ts
  test/grpc/Data.spec.ts
Labels: size/M

#267 docs: typo in README.md
  README.md
Labels: size/XS

#268 support one way tls
  milvus/grpc/BaseClient.ts
  test/grpc/MilvusClient.spec.ts
Labels: size/M

#269 support createCollection({collection_name, schema, index_params});
  milvus/MilvusClient.ts
  milvus/const/milvus.ts
  milvus/grpc/Collection.ts
  milvus/types/Collection.ts
  milvus/types/HighLevel.ts
  milvus/types/MilvusIndex.ts
  milvus/utils/Format.ts
  milvus/utils/Validate.ts
  test/grpc/HighLevel.spec.ts
  test/grpc/Index.spec.ts
  test/tools/collection.ts
Labels: size/L
