Repository milvus-io/milvus-sdk-node, pull requests merged in 2023-04, with the labels that each got.

#134 [Don't merge]Refactoring code base
  README.md
  example/BinarySearch.ts
  example/Cluster.ts
  example/Collection.ts
  example/HelloMilvus.ts
  example/InsertAndIndex.ts
  example/LoadCollectionStatus.ts
  example/Query.ts
  example/Search.ts
  example/TimetravelSearch.ts
  example/User.ts
  milvus/BaseClient.ts
  milvus/Client.ts
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusClient.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/Resource.ts
  milvus/User.ts
  milvus/Utils.ts
  milvus/index.ts
  milvus/types/Common.ts
  milvus/types/User.ts
  milvus/utils/index.ts
  package.json
  test/Alias.spec.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Import.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/MilvusClient.spec.ts
  test/Partition.spec.ts
  test/Replica.spec.ts
  test/Resource.spec.ts
  test/User.spec.ts
  test/Utils.spec.ts
  test/build/Collection.spec.ts
  tsconfig.json
  utils/Blob.ts
  utils/Format.ts
  utils/Function.ts
  utils/Grpc.ts
  utils/Validate.ts
  utils/index.ts
  yarn.lock
Labels: size/XXL

#135 Fixed / improved some error messages
  milvus/const/ErrorReason.ts
Labels: size/S

#140 support getLoadingProgress and getLoadState
  milvus/Collection.ts
  milvus/const/Milvus.ts
  milvus/types/Collection.ts
  test/Collection.spec.ts
Labels: size/L

#141 add more coverage
  example/HelloMilvus.ts
  milvus/Collection.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Utils.spec.ts
  utils/test.ts
Labels: size/L

#143 support dim and max_length in field object
  milvus/Collection.ts
  milvus/const/ErrorReason.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Insert.spec.ts
  test/Utils.spec.ts
  test/build/Collection.spec.ts
  utils/Validate.ts
  utils/test.ts
Labels: size/XL

#146 upgrade @grpc/grpc-js and @grpc/proto-loader and protobufjs to the latest version
  package.json
  yarn.lock
Labels: size/M

#148 support timeout as client param
  example/Collection.ts
  milvus/BaseClient.ts
  milvus/Collection.ts
  milvus/Data.ts
  milvus/MilvusClient.ts
  milvus/MilvusIndex.ts
  milvus/Partition.ts
  milvus/Resource.ts
  milvus/User.ts
  milvus/types/Client.ts
  test/Utils.spec.ts
  utils/Format.ts
  utils/Function.ts
Labels: size/L

#150 Simplify search API
  milvus/Data.ts
  milvus/const/ErrorReason.ts
  milvus/const/Milvus.ts
  milvus/types/Data.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Utils.spec.ts
  test/build/Collection.spec.ts
  test/utils/Format.spec.ts
  test/utils/Validate.spec.ts
  utils/Format.ts
  utils/Validate.ts
  utils/test.ts
Labels: size/XL

#151 make some alias of search params
  milvus/Data.ts
  milvus/types/Data.ts
  test/Data.spec.ts
Labels: size/M
