Repository milvus-io/milvus-sdk-node, pull requests merged in 2023-05, with the labels that each got.

#154 refactor
  milvus/MilvusClient.ts
  milvus/Utils.ts
  milvus/const/index.ts
  milvus/grpc/BaseClient.ts
  milvus/grpc/Collection.ts
  milvus/grpc/Data.ts
  milvus/grpc/GrpcClient.ts
  milvus/grpc/MilvusIndex.ts
  milvus/grpc/Partition.ts
  milvus/grpc/Resource.ts
  milvus/grpc/User.ts
  milvus/index.ts
  milvus/types.ts
  milvus/types/Collection.ts
  milvus/types/Common.ts
  milvus/types/Index.ts
  milvus/types/MilvusIndex.ts
  milvus/types/User.ts
  package.json
  test/MilvusClient.spec.ts
  test/User.spec.ts
  test/Utils.spec.ts
  test/utils/Format.spec.ts
  test/utils/Function.spec.ts
  test/utils/Grpc.spec.ts
  test/utils/Test.spec.ts
  test/utils/Validate.spec.ts
  utils/test.ts
Labels: size/XXL

#155 Insert performance
  milvus/grpc/Data.ts
Labels: size/M

#156 update grpc settings
  milvus/grpc/GrpcClient.ts
  utils/Validate.ts
Labels: size/XS

#157 Create collection support string as data type
  const/index.ts
  example/BinarySearch.ts
  example/Collection.ts
  example/Search.ts
  milvus/const/ErrorReason.ts
  milvus/const/Milvus.ts
  milvus/grpc/BaseClient.ts
  milvus/grpc/Collection.ts
  milvus/grpc/Data.ts
  milvus/grpc/GrpcClient.ts
  milvus/grpc/MilvusIndex.ts
  milvus/grpc/Partition.ts
  milvus/grpc/Resource.ts
  milvus/grpc/User.ts
  milvus/index.ts
  milvus/types/Collection.ts
  milvus/types/Resource.ts
  milvus/utils/Blob.ts
  milvus/utils/Format.ts
  milvus/utils/Function.ts
  milvus/utils/Grpc.ts
  milvus/utils/Validate.ts
  milvus/utils/index.ts
  test/Alias.spec.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Import.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/MilvusClient.spec.ts
  test/Partition.spec.ts
  test/Replica.spec.ts
  test/Resource.spec.ts
  test/User.spec.ts
  test/build/Collection.spec.ts
  test/common/timeout.ts
  test/tools/files/data.json
  test/tools/index.ts
  test/utils/Format.spec.ts
  test/utils/Test.spec.ts
  test/utils/Validate.spec.ts
  tsconfig.json
Labels: size/XL

#163 fix create index on readme
  README.md
Labels: size/XS

#161 if address starts with https, set ssl to true
  milvus/grpc/BaseClient.ts
  test/MilvusClient.spec.ts
Labels: size/S

#169 Dynamic schema
  milvus/const/ErrorReason.ts
  milvus/const/Milvus.ts
  milvus/const/defaults.ts
  milvus/const/index.ts
  milvus/const/limits.ts
  milvus/grpc/Collection.ts
  milvus/grpc/Data.ts
  milvus/types/Collection.ts
  milvus/types/Data.ts
  milvus/utils/Format.ts
  test/DynamicSchema.spec.ts
  test/PartitionKey.spec.ts
  test/tools/index.ts
  test/utils/Format.spec.ts
Labels: size/XL

#171 Fix Database metadata
  milvus/const/client.ts
  milvus/const/index.ts
  milvus/grpc/BaseClient.ts
  milvus/grpc/GrpcClient.ts
  milvus/types/Client.ts
  milvus/utils/Format.ts
  milvus/utils/Grpc.ts
  package.json
  test/Alias.spec.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Database.spec.ts
  test/DynamicSchema.spec.ts
  test/Import.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/MilvusClient.spec.ts
  test/Partition.spec.ts
  test/PartitionKey.spec.ts
  test/Replica.spec.ts
  test/Resource.spec.ts
  test/User.spec.ts
  test/utils/Format.spec.ts
  test/utils/Grpc.spec.ts
  tsconfig.json
Labels: size/XL

#174 adjust grpc default options
  milvus/grpc/BaseClient.ts
  milvus/grpc/GrpcClient.ts
  test/Collection.spec.ts
Labels: size/S

#175 throw incompatible error
  milvus/MilvusClient.ts
  milvus/grpc/GrpcClient.ts
  milvus/utils/Grpc.ts
Labels: size/S

#176 remove all console.log in tests files
  test/Basic.spec.ts
  test/BinarySearch.spec.ts
  test/Collection.spec.ts
  test/Data.spec.ts
  test/Database.spec.ts
  test/DynamicSchema.spec.ts
  test/Index.spec.ts
  test/Insert.spec.ts
  test/MilvusClient.spec.ts
  test/PartitionKey.spec.ts
  test/Replica.spec.ts
  test/Resource.spec.ts
  test/User.spec.ts
  test/build/Collection.spec.ts
Labels: size/L

#177 support consistency_level on query/search
  milvus/grpc/Data.ts
  milvus/types/Data.ts
  milvus/utils/Grpc.ts
  test/Data.spec.ts
  test/DynamicSchema.spec.ts
  test/Import.spec.ts
Labels: size/S
