Repository milvus-io/milvus-sdk-node, pull requests merged in 2024-11, with the labels that each got.

#370 feat(TLS): Support skipCertCheck option to bypass certificate check
  milvus/const/client.ts
  milvus/grpc/BaseClient.ts
  milvus/types/Client.ts
  package.json
  test/grpc/MilvusClient.spec.ts
  yarn.lock
Labels: size/XXL

#373 Passing `db_name` param to the `describeCollection()`
  milvus/grpc/Data.ts
Labels: size/S

#376 [2.5] support bitmap index
  milvus/const/milvus.ts
  milvus/types/Common.ts
  test/grpc/Index.spec.ts
Labels: size/S

#378 Fix 2.5 function tests
  test/grpc/Functions.spec.ts
Labels: size/S

#379 support the properties param in the create database api
  milvus/grpc/Database.ts
  milvus/types/Database.ts
  test/grpc/Database.spec.ts
Labels: size/M

#380 fix: function output field should not be inserted as dynamic field
  milvus/grpc/Data.ts
  milvus/utils/Format.ts
  test/grpc/FullTextSearch.spec.ts
  test/utils/Format.spec.ts
Labels: size/L
