Repository milvus-io/milvus-sdk-node, pull requests merged in 2024-03, with the labels that each got.

#281 fix: vercel deploy error
  examples/nextjs/README.md
  examples/nextjs/app/page.tsx
  examples/nextjs/next.config.js
  examples/nextjs/package.json
  examples/nextjs/pages/api/milvus.ts
  examples/nextjs/yarn.lock
Labels: size/L

#282 add loadPartitionSync
  milvus/grpc/Collection.ts
  milvus/grpc/Partition.ts
  test/grpc/Partition.spec.ts
Labels: size/L

#283 add listIndexes
  milvus/grpc/MilvusIndex.ts
  milvus/types/MilvusIndex.ts
  test/grpc/Index.spec.ts
Labels: size/M

#285 Add sparse vector support
  milvus/HttpClient.ts
  milvus/const/milvus.ts
  milvus/grpc/Data.ts
  milvus/types/Data.ts
  milvus/types/Http.ts
  milvus/utils/Blob.ts
  milvus/utils/Bytes.ts
  milvus/utils/Format.ts
  milvus/utils/Function.ts
  milvus/utils/Validate.ts
  milvus/utils/index.ts
  package.json
  test/grpc/BinaryVector.spec.ts
  test/grpc/Collection.spec.ts
  test/grpc/SparseVector.spec.ts
  test/http/client.spec.ts
  test/tools/collection.ts
  test/tools/data.ts
  test/utils/Bytes.spec.ts
  test/utils/Function.spec.ts
  test/utils/Test.spec.ts
  test/utils/Validate.spec.ts
Labels: size/XL

#287 Support f16 & bf16
  milvus/grpc/Data.ts
  milvus/types/Data.ts
  milvus/types/Http.ts
  milvus/utils/Bytes.ts
  milvus/utils/Format.ts
  milvus/utils/Function.ts
  milvus/utils/Validate.ts
  package.json
  test/grpc/Float16Vector.spec.ts
  test/tools/data.ts
  test/utils/Bytes.spec.ts
  test/utils/Function.spec.ts
  yarn.lock
Labels: size/L

#289 throw more errors if create collection failed with high level api
  milvus/MilvusClient.ts
  test/grpc/HighLevel.spec.ts
Labels: size/M

#291 New retry logic
  milvus/const/defaults.ts
  milvus/utils/Grpc.ts
  milvus/utils/Validate.ts
  test/utils/Validate.spec.ts
Labels: size/L

#293 Support more types of sparse vectors
  milvus/grpc/Data.ts
  milvus/types/Data.ts
  milvus/utils/Bytes.ts
  test/grpc/SparseVector.array.spec.ts
  test/grpc/SparseVector.coo.spec.ts
  test/grpc/SparseVector.csr.spec.ts
  test/grpc/SparseVector.spec.dict.ts
  test/tools/data.ts
  test/utils/Bytes.spec.ts
  test/utils/Test.spec.ts
Labels: size/XL
