Repository milvus-io/milvus-sdk-node, pull requests merged in 2024-06, with the labels that each got.

#313 enhance: add resource group declarative api
  milvus/grpc/Resource.ts
  milvus/types/Resource.ts
  test/grpc/Resource.spec.ts
Labels: size/M

#318 upgrade @grpc/grpc-js
  package.json
  yarn.lock
Labels: size/M

#322 support db_name in APIs
  milvus/types/Collection.ts
  milvus/types/Common.ts
  milvus/types/Data.ts
  milvus/types/Resource.ts
  test/grpc/Database.spec.ts
  test/utils/Format.spec.ts
Labels: size/M

#323 add describeDatabase api
  milvus/grpc/Database.ts
  milvus/types/Database.ts
  test/grpc/Database.spec.ts
Labels: size/M

#324 add listGrant alias
  milvus/grpc/User.ts
  milvus/types/User.ts
  test/grpc/User.spec.ts
Labels: size/M

#328 Add a sparse example
  examples/milvus/Data.ts
  examples/milvus/HelloSparse.ts
Labels: size/L

#329 chore: update example next.js README
  examples/nextjs/README.md
Labels: size/XS
