Repository milvus-io/milvus-sdk-node, pull requests merged in 2024-12, with the labels that each got.

#381 format describe collection response
  milvus/grpc/Data.ts
  milvus/types/Collection.ts
  milvus/types/Common.ts
  milvus/utils/Format.ts
  test/grpc/Collection.spec.ts
  test/grpc/DynamicSchema.spec.ts
  test/tools/collection.ts
  test/utils/Format.spec.ts
Labels: size/L

#382 support insert null
  milvus/grpc/Data.ts
  milvus/types/Collection.ts
  milvus/types/Data.ts
  milvus/utils/Format.ts
  milvus/utils/Grpc.ts
  test/grpc/PartialLoad.spec.ts
  test/tools/collection.ts
  test/tools/data.ts
  test/utils/Format.spec.ts
Labels: size/M

#383 enhance: support hints param
  milvus/types/Data.ts
  milvus/utils/Format.ts
Labels: size/XS

#385 support delete properties for database and collection
  milvus/grpc/Collection.ts
  milvus/grpc/Database.ts
  milvus/types/Collection.ts
  milvus/types/Database.ts
  package.json
  test/grpc/Collection.spec.ts
  test/grpc/Database.spec.ts
Labels: size/L

#387 support recalls in search result
  milvus/grpc/Data.ts
  milvus/types/Data.ts
Labels: size/XS

#388 Add alterIndexProperties and dropIndexProperties
  milvus/grpc/MilvusIndex.ts
  milvus/types/MilvusIndex.ts
  test/grpc/Database.spec.ts
  test/grpc/Index.spec.ts
Labels: size/L

#389 support expr template for query/search/delete
  milvus/grpc/Data.ts
  milvus/types/Common.ts
  milvus/types/Data.ts
  milvus/utils/Format.ts
  test/grpc/Data.spec.ts
  test/grpc/KeywordMatch.spec.ts
  test/utils/Format.spec.ts
Labels: size/L

#390 deprecate alterCollection, use alterCollectionProperties instead
  milvus/grpc/Collection.ts
  test/grpc/Collection.spec.ts
  test/grpc/Database.spec.ts
Labels: size/S

#391 [2.4] support expr template values
  milvus/grpc/Data.ts
  milvus/types/Common.ts
  milvus/types/Data.ts
  milvus/utils/Format.ts
  test/grpc/Data.spec.ts
  test/tools/collection.ts
  test/tools/const.ts
  test/tools/data.ts
  test/utils/Format.spec.ts
Labels: size/L

#392 add alterCollectionFieldProperties API
  milvus/grpc/Collection.ts
  milvus/types/Collection.ts
  milvus/utils/Format.ts
  test/grpc/Collection.spec.ts
  test/utils/Format.spec.ts
Labels: size/L

#393 [2.4] add alterCollectionFieldProperties API
  milvus/grpc/Collection.ts
  milvus/grpc/Data.ts
  milvus/types/Collection.ts
  milvus/types/Common.ts
  milvus/utils/Format.ts
  test/grpc/Collection.spec.ts
  test/utils/Format.spec.ts
Labels: size/L

#394 Add createPrivilegeGroup/dropPrivilegeGroup/listPrivilegeGroups/addPrivilegesToGroup/removePrivilegesFromGroup
  milvus/const/milvus.ts
  milvus/grpc/User.ts
  milvus/types/Common.ts
  milvus/types/User.ts
  test/grpc/User.spec.ts
Labels: size/L

#395 Add grantPrivilegeV2 and revokePrivilegeV2
  milvus/grpc/User.ts
  milvus/types/User.ts
  test/grpc/User.spec.ts
Labels: size/L

#396 add refreshLoad api
  milvus/grpc/Collection.ts
  milvus/types/Collection.ts
  test/grpc/Collection.spec.ts
Labels: size/M

#398 fix: query without output_fields should return all fields
  milvus/grpc/Data.ts
  test/grpc/Data.spec.ts
Labels: size/S

#400 Add backupRBAC and restoreRBAC API
  milvus/grpc/User.ts
  milvus/types/User.ts
  test/grpc/User.spec.ts
Labels: size/L

#402 fix upsert failed on autoid enabled collection
  milvus/grpc/Data.ts
  test/grpc/Upsert.spec.ts
Labels: size/M

#403 Add more test cases for the upsert API
  test/grpc/Upsert.spec.ts
Labels: size/S
