Repository milvus-io/milvus-sdk-node, pull requests merged in 2024-07, with the labels that each got.

#336 support passing certificate buffer
  milvus/grpc/BaseClient.ts
  milvus/types/Client.ts
  test/grpc/MilvusClient.spec.ts
Labels: size/M

#339 fix issue with returning a connection to the pool too early
  milvus/utils/Function.ts
Labels: size/XS

#341 how to check connection
  README.md
  milvus/grpc/GrpcClient.ts
  test/grpc/MilvusClient.spec.ts
Labels: size/S

#343 pref: HttpClient vector search
  milvus/const/error.ts
  milvus/http/Vector.ts
  milvus/types/Http.ts
  package.json
  test/grpc/Data.spec.ts
  test/http/test.ts
Labels: size/M
