Repository milvus-io/milvus-sdk-node, pull requests merged in 2025-05, with the labels that each got.

#432 chore: upgrade nextjs example
  examples/nextjs/app/page.tsx
  examples/nextjs/next.config.js
  examples/nextjs/package.json
  examples/nextjs/yarn.lock
Labels: size/XL

#434 feat: support milvus-lite 2.5
  .github/workflows/test.yml
  .gitignore
  milvus/MilvusLiteClient.ts
  milvus/index.ts
  milvus/lite/MilvusLiteServer.ts
  milvus/lite/start.py
  package.json
  test/build/lite.spec.ts
Labels: size/L

#436 pref: prompt user milvus-lite is not installed
  milvus/lite/MilvusLiteServer.ts
  milvus/lite/start.py
Labels: size/L

#437 feat: proto-json
  .github/workflows/release.yml
  build.js
  milvus/grpc/BaseClient.ts
  milvus/grpc/GrpcClient.ts
  milvus/proto-json/milvus.base.ts
  milvus/proto-json/milvus.ts
  milvus/proto-json/schema.base.ts
  milvus/types/Client.ts
  milvus/utils/Grpc.ts
  package.json
  test/grpc/MilvusClient.spec.ts
  test/utils/ProtoJson.spec.ts
  tsconfig.json
Labels: size/XXL

#438 feat: support ignore schema check on insertion and use the string key to check
  milvus/grpc/Data.ts
  milvus/types/Collection.ts
  milvus/types/Data.ts
  test/utils/Format.spec.ts
Labels: size/S

#444 chore: better query iterator example
  examples/milvus/QueryIterator.ts
Labels: size/S
